# config.yaml

data:
  output_dir: "output/"
  normalize_columns: ["Average_Points", "Next_Year_Price"]
  label_threshold: 0.30
  test_year: 2024

model:
  input_dropout: 0.3
  hidden_dims: [256, 128, 64, 32]
  output_dropout: 0.3

training:
  batch_size: 64
  epochs: 2000
  learning_rate: 0.001
  patience: 25
  save_path: "output/training/mlp_breakout_model.pt"

logging:
  log_file: "output/training/training_log.txt"

distill:
  cart:
    output_dir: "output/distill/cart/"
    mode: "classification"     
    max_depth: 9
    min_samples_leaf: 8
    ccp_alpha: 0.001           # light pruning for stability
    k_top_picks: 22
    random_trials: 100

    # turn off global weighting while we tune the band
    weight_top_quantile: 0.0
    top_weight: 1.0
    rest_weight: 1.0

    # surgical top-focus training
    top_focus_enabled: true
    focus_by_k: true           # match K/|val| density in train
    focus_top_fraction: 0.05   # ignored when focus_by_k=true
    neg_band_width: 0.03       # narrow band just below positive threshold
    pos_weight: 35.0
    neg_weight: 1.0